@startuml
'https://plantuml.com/use-case-diagram
 

left to right direction

actor Teacher as "Geography Teacher"
rectangle database

rectangle "Population System" {
        
        usecase UC1 as "Produce several reports \nregarding countries"
        usecase UC2 as "Produce several reports \nregarding cities"
        usecase UC3 as "Produce several reports \nregarding capital cities"
        usecase UC4 as "Produce several reports \nregarding population \nand languages"

        Teacher -- UC1
        Teacher -- UC2
        Teacher -- UC3
        Teacher -- UC4
        
        UC1 -- database
        UC2 -- database
        UC3 -- database
        UC4 -- database
        
}
@enduml