@startuml
'https://plantuml.com/use-case-diagram
 

left to right direction

actor Teacher as "Geography Teacher"
rectangle database

rectangle "Population System" {
        
        usecase UC1 as "Use Case 1"
        usecase UC2 as "Use Case 2"
        usecase UC3 as "Use Case 3"
        usecase UC4 as "Use Case 4"

        Teacher -- UC1
        Teacher -- UC2
        Teacher -- UC3
        Teacher -- UC4
        
        UC1 -- database
        UC2 -- database
        UC3 -- database
        UC4 -- database
        
}
@enduml